server:
  port: 8016

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/wanted
    username: wanted
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:initdb/insert_test_data.sql
      schema-locations: classpath:initdb/create_schema.sql
      encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

